### ISSUE TITLE
Design and develop a dashboard that translates LDAP-to-naftoken auth

### ISSUE THREAD

**Issue by thiagomanel** [fogbow/fogbow-dashboard#12]
The idea is to have a dashboard able to talk to a NAF-based fogbow manager without interacting with the  shibboleth federation. It would be nice to use it within a fogbow site.

That ideia is to authenticate using LDAP, then generate a NAF-token based on LDAP information.

**Comment by thiagomanel** [comment]
The token generated by this dashboard shall have the both the ldap and expiration information. It should be possible to use a `--saml` option to include saml information into the token

**Comment by gustavorag** [comment]
LDAP Authentication developed.
